#
# DAL Deployment script for CentOS 7
# Copyright (c) 2016, Diversity Arrays Technology, All rights reserved.
#
# Author: Puthick Hok
# Date: 08/08/2016
# Usage: ansible-playbook kddart_server_deployment_centos7.yml
# Description: By running the usage command, ansible will install and configure DAL
#              according the instructions in kddart_server_deployment_centos7.yml.
#              This script needs to be run by root.
#              For more information about how to read and write an ansible playbook,
#              please refer to ansible documentation on the web.
#

- hosts: kddartserver
  gather_facts: no

  vars_prompt:
    - name: "local_tar_gz_file"
      prompt: "Enter the source tar.gz file of KDDart wih either relative or full path."
      private: no

    - name: "mysqlrootpass"
      prompt: "Enter MySQL root password. If you run this ansible playbook for the first time, this will be your MySQL password and it can be anything as long as it is 8 characters long with number, captial letter and symbol. If you run this playbook before, this password must be the same as the one you used in the very first run."
      private: yes

    - name: "dbpass"
      prompt: "Password for kddart_dal user (min 8 chars and with number, capital and symbol)"
      private: yes

    - name: "ip_network"
      prompt: "Enter IP network of the target machine, eg. 192.168.78.0/24"
      private: no

  vars:
    src_file:  /root/KDDArT-DAL-v2.3.2.tar.gz
    dal_version: v2.3.2
    dal_db_version: v2_3_2
    local_dir: /root/KDDArT-DAL-{{ dal_version }}
    apache_base_dir: /var/www
    dest_apache_conf_dir: /etc/httpd/conf.d
    main_apache_conf: /etc/httpd/conf/httpd.conf
    apache_module_conf: /etc/httpd/conf.modules.d/00-base.conf
    local_src_dir: /usr/local
    force_tasks: True
    monetdbpass: monetdb
    postgrespass: '{{ dbpass }}'
    dal_address_name: kddart.example.com

  tasks:

    - name: Copy the tar.gz file
      copy: src={{ local_tar_gz_file }} dest={{ src_file }}

    - name: Create local_dir
      shell: "[[ -d {{ local_dir }} ]] || mkdir {{ local_dir }}"

    - name: Untar and decompress KDDart source
      shell: >
        if [ -d {{ local_dir }} ]; then 
        cd {{ local_dir }};
        tar -zxvf {{ src_file }} --strip 1;
        fi;

    - include: ./kddart_dal_v2_3_2_server_deployment_centos7.yml
      static: yes